# Generated by Django 4.2.6 on 2023-12-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staffs", "0002_auto_20201124_0614"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff",
            name="date_of_admission",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="other_name",
        ),
        migrations.AddField(
            model_name="staff",
            name="identifiant",
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="staff",
            name="current_status",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="staff",
            name="gender",
            field=models.CharField(
                choices=[("homme", "Homme"), ("femme", "Femme")],
                default="male",
                max_length=10,
            ),
        ),
    ]
