# Generated by Django 4.2.6 on 2023-12-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staffs", "0004_alter_staff_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="identifiant",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
