# Generated by Django 4.2.6 on 2023-12-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="diplomaver",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "diplom",
                    models.FileField(blank=True, upload_to="students/diplomaver/"),
                ),
            ],
        ),
    ]
