# Generated by Django 4.2.6 on 2023-12-19 23:44

from django.db import migrations, models



class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="user",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surname", models.CharField(max_length=200)),
                ("firstname", models.CharField(max_length=200)),
                ("identifiant", models.CharField(max_length=200, unique=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("homme", "Homme"), ("femme", "Femme")],
                        default="male",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
