# Generated by Django 4.2.6 on 2023-12-17 01:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0003_alter_student_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="registration_number",
            new_name="identifiant",
        ),
    ]
