# Generated by Django 4.2.6 on 2023-12-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0006_alter_student_diplom"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="password",
            field=models.CharField(default="a", max_length=200),
        ),
        migrations.AddField(
            model_name="student",
            name="username",
            field=models.CharField(default="a", max_length=200),
        ),
    ]
