# Generated by Django 4.2.6 on 2023-12-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0007_student_password_student_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="password",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="student",
            name="username",
            field=models.CharField(max_length=200),
        ),
    ]
