# Generated by Django 4.2.6 on 2023-12-20 00:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0008_alter_student_password_alter_student_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
