# Generated by Django 4.2.6 on 2023-12-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0009_alter_student_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="diplomcod",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
