# Generated by Django 4.2.6 on 2023-12-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0010_student_diplomcod"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="diplomcod",
            field=models.TextField(blank=True, null=True),
        ),
    ]
