# Generated by Django 4.2.6 on 2023-12-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0011_alter_student_diplomcod"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="diplomcod",
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
