# Generated by Django 4.2.6 on 2023-12-20 23:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0013_alter_student_diplomcod"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={},
        ),
    ]
