# Generated by Django 4.2.6 on 2023-12-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0015_studeblock"),
    ]

    operations = [
        migrations.AddField(
            model_name="studeblock",
            name="hashcode",
            field=models.TextField(db_column="hashcode", null=True),
        ),
        migrations.AddField(
            model_name="studeblock",
            name="previoushash",
            field=models.TextField(db_column="previoushash", null=True),
        ),
    ]
